name: Deploy to Catalyst

on:
  push:
    branches:
      - main   # or 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Catalyst CLI
        run: npm install -g zcatalyst-cli

      - name: Restore Catalyst Auth
        run: |
          echo "${{ secrets.CATALYST_AUTH }}" > auth.json
          catalyst auth:import --file auth.json

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build && npm run export

      - name: Deploy to Catalyst
        run: catalyst deploy
