name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main   # 👈 deploy whenever you push to main

permissions:
  contents: write   # 👈 allow GitHub Actions to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the Next.js project
      - name: Build project
        run: npm run build

      # Export static files (needs output: "export" in next.config.js)
      - name: Export static files
        run: npm run export

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
